application:
  limiter:
    threshold: 300000
    scheduled-time: 300000
  api:
    weather:
      url:  https://api.openweathermap.org/data/
      version: 3.0
      key: ${OPEN_WEATHER_API}

spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

server:
  port: 8080
  servlet:
    context-path: /api/v1/
  cors:
    origins: http://localhost:3001

